Repository JupiterOne/graph-servicenow, pull requests merged in 2024-07, with the labels that each got.

#54 Added ingestion of multiple cmdb classes
  CHANGELOG.md
  src/__recordings__/validateInvocationPassesWithBadCMDBClasses_2534101251/recording.har
  src/__recordings__/validateInvocationPassesWithBadCMDBParent_4213239449/recording.har
  src/ingestionConfig.ts
  src/steps/cmdb/__recordings__/step-cmdb_3257228988/recording.har
  src/steps/cmdb/index.ts
  src/util/__recordings__/validate-multiple-classes-1_1467258337/recording.har
  src/util/__recordings__/validate-multiple-classes-2_1416925480/recording.har
  src/util/__recordings__/validate-multiple-classes_3706453795/recording.har
  src/util/cmdbHierarchyUtils.ts
  src/util/validateMultipleClasses.test.ts
  src/validateInvocation.test.ts
  src/validateInvocation.ts
Labels: release, minor

#55 Custom Field Casing
  CHANGELOG.md
  package.json
  src/steps/cmdb/__snapshots__/converters.test.ts.snap
  src/steps/cmdb/converters.ts
  yarn.lock
Labels: release, major

#56 Int 11375
  src/util/cmdbHierarchyUtils.ts
  src/validateInvocation.ts
Labels: patch, release

#57 Added error logging
  src/util/cmdbHierarchyUtils.ts
Labels: patch, release
